# Generated by Django 4.2.2 on 2023-06-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaldict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.users')),
            ],
            options={
                'db_table': 'PersonalDict',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255)),
                ('translation', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'Words',
            },
        ),
        migrations.CreateModel(
            name='Wordsindict',
            fields=[
                ('dict', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dictionary.personaldict')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionary.words')),
            ],
            options={
                'db_table': 'WordsInDict',
            },
        ),
    ]
