# Generated by Django 4.2.2 on 2023-06-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255)),
                ('password', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
